development: &DEFAULT
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: advanced_capybara_dev
  pool: 5
  username: elabs
  password:
  min_messages: warning

test:
  <<: *DEFAULT
  database: advanced_capybara_test
